#!/bin/sh
# Regenerates deploy/k8s/base/prometheusrule.yaml from deploy/prometheus-alerts.yaml.
#
# deploy/prometheus-alerts.yaml is the single source of truth for the alert
# rules and stays usable by a plain Prometheus (rule_files:). A PrometheusRule's
# spec is exactly that document, indented one level, so this script wraps it
# instead of keeping a second copy. Run it whenever the alerts change; the diff
# it produces IS the drift check.
set -eu

here=$(dirname "$0")
alerts="$here/../prometheus-alerts.yaml"
out="$here/base/prometheusrule.yaml"

[ -f "$alerts" ] || { echo "sync-alerts: $alerts not found" >&2; exit 1; }

{
  cat <<'HEADER'
# GENERATED by deploy/k8s/sync-alerts.sh from deploy/prometheus-alerts.yaml.
# Do not edit here -- edit the alert file and re-run the script.
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mediaserverd
  labels:
    app.kubernetes.io/name: mediaserver
    release: prometheus
spec:
HEADER
  # The alert file is CRLF in this repo; normalise so the generated manifest
  # is not half one thing and half the other.
  tr -d '\r' < "$alerts" | sed 's/^\(.\)/  \1/'
} > "$out"

echo "sync-alerts: wrote $out from $alerts"
