#!/bin/sh
# Regenerates this overlay for a different media port range.
#
#   ./regenerate.sh 40100 40119
#
# It rewrites deployment-hostport.yaml (one containerPort/hostPort entry per UDP
# port -- Kubernetes has no way to express a range) and media-range.yaml (the
# two ConfigMap values mediaserverd itself reads). Keep the two in step: a
# hostPort MSS never binds is a scheduling cost for nothing, and a port MSS
# binds without a hostPort is a tap with no audio.
set -eu

lo=${1:?usage: regenerate.sh <port-min> <port-max>}
hi=${2:?usage: regenerate.sh <port-min> <port-max>}

[ "$lo" -le "$hi" ] || { echo "regenerate: $lo is above $hi" >&2; exit 2; }
count=$((hi - lo + 1))
legs=$((count / 2))

here=$(dirname "$0")

{
  cat <<HEADER
# GENERATED by ./regenerate.sh $lo $hi -- rerun it rather than editing by hand.
#
# hostPort variant: the pod keeps the pod network, and each media UDP port is
# mapped through to the same port on the node.
#
# THE TRADE-OFF. A hostPort cannot express a RANGE -- Kubernetes maps one port
# per entry, so a range costs one containerPort entry per port and the scheduler
# treats every one of them as a node resource. That caps the range at something
# hand-maintainable, which caps concurrent tapped calls: the $count ports below
# are $legs even ports = $legs tapped legs = $((legs / 2)) two-party calls per pod.
# It also means only ONE pod per node (the second collides on every port), so
# the anti-affinity below is required, not preferred. In exchange you keep
# pod-network isolation, NetworkPolicy, and a CNI you do not have to reason
# about.
#
# Choose this when the media volume is modest and the platform team will not
# allow hostNetwork. Choose ../hostnetwork when the range has to be wide.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaserverd
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: mediaserver
                  app.kubernetes.io/component: media-plane
      containers:
        - name: mediaserverd
          env:
            # rtpengine must be told the NODE's address, because that is where
            # the hostPort mapping lives -- the pod IP is unreachable from
            # outside the cluster network.
            - name: MSS_MEDIA_ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          ports:
            # Media, one entry per UDP port in MSS_MEDIA_PORT_MIN..MAX. Even
            # ports carry RTP; the odd successors are mapped too so the range in
            # the firewall, in the ConfigMap and here are the same numbers.
HEADER
  port=$lo
  while [ "$port" -le "$hi" ]; do
    printf '            - containerPort: %s\n              hostPort: %s\n              protocol: UDP\n' "$port" "$port"
    port=$((port + 1))
  done
} > "$here/deployment-hostport.yaml"

cat > "$here/media-range.yaml" <<RANGE
# GENERATED by ./regenerate.sh $lo $hi -- rerun it rather than editing by hand.
# The range mediaserverd binds inside. Even ports only are handed out, so these
# $count ports serve $legs tapped legs ($((legs / 2)) two-party calls).
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediaserverd-env
data:
  MSS_MEDIA_PORT_MIN: "$lo"
  MSS_MEDIA_PORT_MAX: "$hi"
RANGE

echo "regenerate: $count ports ($lo-$hi), $legs tapped legs, $((legs / 2)) two-party calls per pod"
