"""A mock event-bus translator, built to measure barge-in cut-through.

Barge-in in a real deployment is a chain of four hops:

  1. a consumer (ASR/voice-AI) decides the caller started speaking and tells
     MSS about it;
  2. MSS publishes that as a MediaEvent on Kafka `mss.events`;
  3. somebody's translator consumes the event and decides to cut the prompt;
  4. that translator calls StopPlayback on MediaControl and MSS stops the
     media.

Hops 2-4 are MSS's contract. Hop 1 has no wire today: session-core's
`Registry::report` (ConsumerEvent -> SpeechStarted/Partial/Final) is
reachable only from unit tests -- neither the WS_TWILIO inbound dialect nor
the gRPC ConsumerToServer stream carries a speech report, and the WS `clear`
message takes a different road entirely (a direct rtpengine `stop media`,
never an event). So this script measures hops 2-4 and says so.

The trigger event is therefore PlaybackStarted, not SpeechStarted. That
costs nothing in fidelity for the bus half: every MediaEvent goes through
the same event_pump, the same topic and the same per-external-id partition
key regardless of which payload it carries. What it does NOT cover is the
consumer's own detection latency and whatever hop 1 will cost once it
exists.

This script plays both integrator roles at once, on purpose: it starts the
playback AND barges it. That way every interval it reports is measured on a
single clock (the host's), with no container/host skew in the headline
number. The `at`-based numbers -- MSS's own event timestamp -- are reported
too, next to a measured skew estimate, so their error bar is visible.

Per iteration it records:

  start_to_event_ms   StartPlayback acked -> the event is in this process
  decide_ms           event in hand -> StopPlayback acked  (the translator half)
  cut_through_ms      StartPlayback acked -> StopPlayback acked (the headline)
  bus_ms              MSS's event `at` -> the event is in this process (skewed)
  stop_to_stopped_ms  StopPlayback acked -> PlaybackStopped consumed

Skew is estimated per iteration from the PlaybackStopped event: MSS stamps
it inside the StopPlayback call, so its `at` must fall between this
process's send and ack of that RPC; the offset from the midpoint of that
window is the clock skew, bounded by the RPC's own round trip.

Needs, on the host: pip install --user grpcio grpcio-tools kafka-python-ng
Stubs are generated by lab/barge_drill.sh into lab/out/pb.
"""

import json
import math
import os
import struct
import sys
import time
import wave

STUBS = os.environ.get("STUBS", "lab/out/pb")
sys.path.insert(0, STUBS)

import grpc  # noqa: E402
from kafka import KafkaConsumer  # noqa: E402

import mediacontrol_pb2 as pb  # noqa: E402
import mediacontrol_pb2_grpc as pb_grpc  # noqa: E402

BROKERS = os.environ.get("BROKERS", "127.0.0.1:19092")
TOPIC = os.environ.get("TOPIC", "mss.events")
CONTROL = os.environ.get("CONTROL", "127.0.0.1:50551")
EXTERNAL_ID = os.environ.get("EXTERNAL_ID", "barge-drill")
ITERATIONS = int(os.environ.get("ITERATIONS", "25"))
GAP_SECONDS = float(os.environ.get("GAP_SECONDS", "0.7"))
TONE_SECONDS = float(os.environ.get("TONE_SECONDS", "3"))
TONE_HZ = float(os.environ.get("TONE_HZ", "440"))
WAIT_SECONDS = float(os.environ.get("WAIT_SECONDS", "10"))
OUT = os.environ.get("OUT", "lab/out/barge-drill.jsonl")
TOKEN = os.environ.get("MSS_AUTH_TOKEN", "")

SAMPLE_RATE = 8000
MAX_BLOB_BYTES = 60_000


def log(message):
    print(f"barge-translator: {message}", flush=True)


def tone_wav():
    samples = int(SAMPLE_RATE * TONE_SECONDS)
    frames = b"".join(
        struct.pack("<h", int(8000 * math.sin(2 * math.pi * TONE_HZ * n / SAMPLE_RATE)))
        for n in range(samples)
    )
    path = os.path.join(os.path.dirname(OUT) or ".", "barge-tone.wav")
    with wave.open(path, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE)
        handle.writeframes(frames)
    blob = open(path, "rb").read()
    if len(blob) > MAX_BLOB_BYTES:
        raise SystemExit(
            f"a {len(blob)} byte tone exceeds the {MAX_BLOB_BYTES} byte "
            "single-datagram playback cap; lower TONE_SECONDS"
        )
    log(f"trigger prompt is {TONE_SECONDS}s of {TONE_HZ}Hz, {len(blob)} bytes")
    return blob


def event_at(event):
    return event.at.seconds + event.at.nanos / 1e9


def percentile(values, fraction):
    ordered = sorted(values)
    if not ordered:
        return float("nan")
    rank = max(0, math.ceil(fraction * len(ordered)) - 1)
    return ordered[rank]


def summarize(name, values):
    return {
        "metric": name,
        "n": len(values),
        "p50_ms": round(percentile(values, 0.50), 2),
        "p95_ms": round(percentile(values, 0.95), 2),
        "max_ms": round(max(values), 2) if values else float("nan"),
        "min_ms": round(min(values), 2) if values else float("nan"),
    }


class Bus:
    def __init__(self):
        self.consumer = KafkaConsumer(
            TOPIC,
            bootstrap_servers=BROKERS,
            auto_offset_reset="latest",
            enable_auto_commit=False,
            fetch_max_wait_ms=1,
            fetch_min_bytes=1,
        )
        deadline = time.time() + 30
        while not self.consumer.assignment() and time.time() < deadline:
            self.consumer.poll(timeout_ms=200)
        if not self.consumer.assignment():
            raise SystemExit(f"never got an assignment on {TOPIC} at {BROKERS}")
        self.consumer.poll(timeout_ms=500)
        log(f"subscribed at the end of {TOPIC}: {sorted(self.consumer.assignment())}")

    def drain(self):
        while self.consumer.poll(timeout_ms=20):
            pass

    def wait_for(self, payload, playback_id, timeout):
        deadline = time.time() + timeout
        while time.time() < deadline:
            batches = self.consumer.poll(timeout_ms=5)
            arrival = time.time()
            for records in batches.values():
                for record in records:
                    event = pb.MediaEvent()
                    event.ParseFromString(record.value)
                    if event.external_id != EXTERNAL_ID:
                        continue
                    if event.WhichOneof("payload") != payload:
                        continue
                    carried = getattr(event, payload).playback_id
                    if carried != playback_id:
                        continue
                    return arrival, event
        return None, None


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: barge_translator.py <session-id>")
    session_id = sys.argv[1]
    blob = tone_wav()
    bus = Bus()

    channel = grpc.insecure_channel(CONTROL)
    stub = pb_grpc.MediaControlStub(channel)
    metadata = [("authorization", f"Bearer {TOKEN}")] if TOKEN else []
    stub.DescribeSession(pb.SessionRef(session_id=session_id), metadata=metadata)

    warm = []
    for _ in range(10):
        before = time.time()
        stub.DescribeSession(pb.SessionRef(session_id=session_id), metadata=metadata)
        warm.append((time.time() - before) * 1000)
    log(f"control-plane baseline DescribeSession p50 {percentile(warm, 0.5):.2f} ms")

    rows = []
    misses = 0
    for iteration in range(ITERATIONS):
        bus.drain()
        request = pb.StartPlaybackRequest(
            session=pb.SessionRef(session_id=session_id), blob=blob
        )
        start_sent = time.time()
        playback = stub.StartPlayback(request, metadata=metadata)
        start_acked = time.time()

        arrival, started = bus.wait_for(
            "playback_started", playback.playback_id, WAIT_SECONDS
        )
        if arrival is None:
            misses += 1
            log(f"iteration {iteration}: no PlaybackStarted reached the bus")
            continue

        stop_sent = time.time()
        stub.StopPlayback(
            pb.PlaybackRef(playback_id=playback.playback_id), metadata=metadata
        )
        stop_acked = time.time()

        stopped_at, stopped = bus.wait_for(
            "playback_stopped", playback.playback_id, WAIT_SECONDS
        )

        row = {
            "iteration": iteration,
            "playback_id": playback.playback_id,
            "start_to_event_ms": (arrival - start_acked) * 1000,
            "decide_ms": (stop_acked - arrival) * 1000,
            "cut_through_ms": (stop_acked - start_acked) * 1000,
            "start_rpc_ms": (start_acked - start_sent) * 1000,
            "stop_rpc_ms": (stop_acked - stop_sent) * 1000,
            "bus_ms": (arrival - event_at(started)) * 1000,
        }
        if stopped is not None:
            row["stop_to_stopped_ms"] = (stopped_at - stop_acked) * 1000
            row["skew_ms"] = (
                event_at(stopped) - (stop_sent + stop_acked) / 2
            ) * 1000
        rows.append(row)
        log(
            "iteration {iteration}: cut_through {cut_through_ms:.1f} ms "
            "(bus {start_to_event_ms:.1f} + decide {decide_ms:.1f})".format(**row)
        )
        time.sleep(GAP_SECONDS)

    with open(OUT, "w") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")

    if not rows:
        raise SystemExit("no iteration completed; nothing to report")

    metrics = [
        "cut_through_ms",
        "start_to_event_ms",
        "decide_ms",
        "bus_ms",
        "stop_rpc_ms",
        "start_rpc_ms",
        "stop_to_stopped_ms",
    ]
    summary = {
        "iterations_requested": ITERATIONS,
        "iterations_measured": len(rows),
        "events_missed": misses,
        "broker": BROKERS,
        "topic": TOPIC,
        "control": CONTROL,
        "skew_estimate_ms": round(
            percentile([row["skew_ms"] for row in rows if "skew_ms" in row], 0.5), 2
        ),
        "stats": [
            summarize(name, [row[name] for row in rows if name in row])
            for name in metrics
        ],
    }
    print(json.dumps(summary, indent=2), flush=True)
    log(f"per-iteration rows in {OUT}")


if __name__ == "__main__":
    main()
