"""A mock event-bus translator, built to measure barge-in cut-through.

Barge-in in a real deployment is a chain of four hops:

  1. a consumer (ASR/voice-AI) decides the caller started speaking and tells
     MSS about it;
  2. MSS publishes that as a MediaEvent on Kafka `mss.events`;
  3. somebody's translator consumes the event and decides to cut the prompt;
  4. that translator calls StopPlayback on MediaControl and MSS stops the
     media.

All four hops are measured here, and all four are MSS's contract as of
D19's fix: hop 1 now has a wire. A gRPC consumer holding CAPABILITY_EVENTS
sends ConsumerToServer.SpeechReport on its MediaStream.Subscribe stream, and
MSS turns it into the MediaEvent the report names. (The WS-Twilio dialect
still has no such message and never will -- its bytes are frozen -- so a WS
consumer cannot report speech; the WS `clear` message takes a different road
entirely, a direct rtpengine `stop media` that never becomes an event.)

The trigger is therefore a real SpeechReport(STARTED): this process attaches
as the gRPC consumer, says "the human started talking", and then barges the
prompt as the translator. What is still out of frame is the consumer's own
DETECTION latency -- how long an ASR takes to decide speech began. Nothing
in MSS can measure that; it belongs to whatever consumer an integrator runs.

This script plays every integrator role at once, on purpose: it starts the
playback, reports the speech AND barges it. That way every interval it
reports is measured on a single clock (the host's), with no container/host
skew in the headline number. The `at`-based numbers -- MSS's own event
timestamp -- are reported too, next to a measured skew estimate, so their
error bar is visible.

Per iteration it records:

  start_to_playing_ms  StartPlayback acked -> PlaybackStarted in this process
  report_to_event_ms   SpeechReport sent -> SpeechStarted in this process
                       (hops 1-2: the consumer's wire plus the bus)
  decide_ms            event in hand -> StopPlayback acked (the translator half)
  cut_through_ms       SpeechReport sent -> StopPlayback acked (the headline)
  bus_ms               MSS's event `at` -> the event is in this process (skewed)
  stop_to_stopped_ms   StopPlayback acked -> PlaybackStopped consumed

Skew is estimated per iteration from the PlaybackStopped event: MSS stamps
it inside the StopPlayback call, so its `at` must fall between this
process's send and ack of that RPC; the offset from the midpoint of that
window is the clock skew, bounded by the RPC's own round trip.

Needs, on the host: pip install --user grpcio grpcio-tools kafka-python-ng
Stubs (mediacontrol AND mediastream) are generated by lab/barge_drill.sh
into lab/out/pb.
"""

import json
import math
import os
import queue
import struct
import sys
import threading
import time
import wave

STUBS = os.environ.get("STUBS", "lab/out/pb")
sys.path.insert(0, STUBS)

import grpc  # noqa: E402
from kafka import KafkaConsumer  # noqa: E402

import mediacontrol_pb2 as pb  # noqa: E402
import mediacontrol_pb2_grpc as pb_grpc  # noqa: E402
import mediastream_pb2 as sb  # noqa: E402
import mediastream_pb2_grpc as sb_grpc  # noqa: E402

BROKERS = os.environ.get("BROKERS", "127.0.0.1:19092")
TOPIC = os.environ.get("TOPIC", "mss.events")
CONTROL = os.environ.get("CONTROL", "127.0.0.1:50551")
EXTERNAL_ID = os.environ.get("EXTERNAL_ID", "barge-drill")
ATTACHMENT = os.environ.get("ATTACHMENT", "")
ITERATIONS = int(os.environ.get("ITERATIONS", "25"))
GAP_SECONDS = float(os.environ.get("GAP_SECONDS", "0.7"))
TONE_SECONDS = float(os.environ.get("TONE_SECONDS", "3"))
TONE_HZ = float(os.environ.get("TONE_HZ", "440"))
WAIT_SECONDS = float(os.environ.get("WAIT_SECONDS", "10"))
OUT = os.environ.get("OUT", "lab/out/barge-drill.jsonl")
TOKEN = os.environ.get("MSS_AUTH_TOKEN", "")

SAMPLE_RATE = 8000
MAX_BLOB_BYTES = 60_000


def log(message):
    print(f"barge-translator: {message}", flush=True)


def tone_wav():
    samples = int(SAMPLE_RATE * TONE_SECONDS)
    frames = b"".join(
        struct.pack("<h", int(8000 * math.sin(2 * math.pi * TONE_HZ * n / SAMPLE_RATE)))
        for n in range(samples)
    )
    path = os.path.join(os.path.dirname(OUT) or ".", "barge-tone.wav")
    with wave.open(path, "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(SAMPLE_RATE)
        handle.writeframes(frames)
    blob = open(path, "rb").read()
    if len(blob) > MAX_BLOB_BYTES:
        raise SystemExit(
            f"a {len(blob)} byte tone exceeds the {MAX_BLOB_BYTES} byte "
            "single-datagram playback cap; lower TONE_SECONDS"
        )
    log(f"trigger prompt is {TONE_SECONDS}s of {TONE_HZ}Hz, {len(blob)} bytes")
    return blob


def event_at(event):
    return event.at.seconds + event.at.nanos / 1e9


def percentile(values, fraction):
    ordered = sorted(values)
    if not ordered:
        return float("nan")
    rank = max(0, math.ceil(fraction * len(ordered)) - 1)
    return ordered[rank]


def summarize(name, values):
    return {
        "metric": name,
        "n": len(values),
        "p50_ms": round(percentile(values, 0.50), 2),
        "p95_ms": round(percentile(values, 0.95), 2),
        "max_ms": round(max(values), 2) if values else float("nan"),
        "min_ms": round(min(values), 2) if values else float("nan"),
    }


class Bus:
    def __init__(self):
        self.consumer = KafkaConsumer(
            TOPIC,
            bootstrap_servers=BROKERS,
            auto_offset_reset="latest",
            enable_auto_commit=False,
            fetch_max_wait_ms=1,
            fetch_min_bytes=1,
        )
        deadline = time.time() + 30
        while not self.consumer.assignment() and time.time() < deadline:
            self.consumer.poll(timeout_ms=200)
        if not self.consumer.assignment():
            raise SystemExit(f"never got an assignment on {TOPIC} at {BROKERS}")
        self.consumer.poll(timeout_ms=500)
        log(f"subscribed at the end of {TOPIC}: {sorted(self.consumer.assignment())}")

    def drain(self):
        while self.consumer.poll(timeout_ms=20):
            pass

    def wait_for(self, payload, timeout, playback_id=None, after_seq=None):
        deadline = time.time() + timeout
        while time.time() < deadline:
            batches = self.consumer.poll(timeout_ms=5)
            arrival = time.time()
            for records in batches.values():
                for record in records:
                    event = pb.MediaEvent()
                    event.ParseFromString(record.value)
                    if event.external_id != EXTERNAL_ID:
                        continue
                    if event.WhichOneof("payload") != payload:
                        continue
                    if playback_id is not None:
                        if getattr(event, payload).playback_id != playback_id:
                            continue
                    if after_seq is not None and event.seq <= after_seq:
                        continue
                    return arrival, event
        return None, None


class Consumer:
    """The gRPC consumer role: subscribes, then reports speech on the wire.

    A tapped session pushes ~50 audio frames a second down this stream, and
    the server drops the consumer when its outbound queue backs up, so the
    responses have to be drained on a thread whether or not we look at them.
    """

    def __init__(self, attachment):
        self.outbound = queue.Queue()
        self.channel = grpc.insecure_channel(CONTROL)
        stub = sb_grpc.MediaStreamStub(self.channel)
        self.responses = stub.Subscribe(self._requests())
        self.outbound.put(
            sb.ConsumerToServer(
                hello=sb.ConsumerHello(attachment_id=attachment, token=TOKEN)
            )
        )
        self.started = threading.Event()
        self.failure = None
        self.frames = 0
        self.drain = threading.Thread(target=self._drain, daemon=True)
        self.drain.start()
        if not self.started.wait(timeout=15):
            raise SystemExit(f"no StreamStart arrived for attachment {attachment}")
        log(f"attached as the grpc consumer on {attachment}")

    def _requests(self):
        while True:
            message = self.outbound.get()
            if message is None:
                return
            yield message

    def _drain(self):
        try:
            for message in self.responses:
                which = message.WhichOneof("msg")
                if which == "start":
                    self.started.set()
                elif which == "frame":
                    self.frames += 1
                elif which == "stop":
                    self.failure = f"the server stopped the stream: {message.stop.reason}"
                    return
        except grpc.RpcError as error:
            self.failure = f"{error.code()}: {error.details()}"
        finally:
            self.started.set()

    def report_speech_started(self, track="customer"):
        if self.failure:
            raise SystemExit(f"the consumer stream is gone -- {self.failure}")
        observed = time.time()
        report = sb.SpeechReport(
            kind=sb.SPEECH_REPORT_KIND_STARTED,
            track=track,
        )
        report.observed_at.seconds = int(observed)
        report.observed_at.nanos = int((observed % 1) * 1e9)
        self.outbound.put(sb.ConsumerToServer(report=report))
        return observed

    def close(self):
        self.outbound.put(None)
        self.channel.close()


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: barge_translator.py <session-id>")
    session_id = sys.argv[1]
    blob = tone_wav()
    bus = Bus()

    channel = grpc.insecure_channel(CONTROL)
    stub = pb_grpc.MediaControlStub(channel)
    metadata = [("authorization", f"Bearer {TOKEN}")] if TOKEN else []
    stub.DescribeSession(pb.SessionRef(session_id=session_id), metadata=metadata)

    warm = []
    for _ in range(10):
        before = time.time()
        stub.DescribeSession(pb.SessionRef(session_id=session_id), metadata=metadata)
        warm.append((time.time() - before) * 1000)
    log(f"control-plane baseline DescribeSession p50 {percentile(warm, 0.5):.2f} ms")

    if not ATTACHMENT:
        raise SystemExit(
            "ATTACHMENT is required: the grpc consumer attachment that reports "
            "speech (mss_ctl <endpoint> consume <external-id>)"
        )
    consumer = Consumer(ATTACHMENT)

    rows = []
    misses = 0
    for iteration in range(ITERATIONS):
        bus.drain()
        request = pb.StartPlaybackRequest(
            session=pb.SessionRef(session_id=session_id), blob=blob
        )
        start_sent = time.time()
        playback = stub.StartPlayback(request, metadata=metadata)
        start_acked = time.time()

        playing_at, started = bus.wait_for(
            "playback_started", WAIT_SECONDS, playback_id=playback.playback_id
        )
        if playing_at is None:
            misses += 1
            log(f"iteration {iteration}: no PlaybackStarted reached the bus")
            continue

        reported = consumer.report_speech_started()
        arrival, speech = bus.wait_for(
            "speech_started", WAIT_SECONDS, after_seq=started.seq
        )
        if arrival is None:
            misses += 1
            log(f"iteration {iteration}: no SpeechStarted reached the bus")
            stub.StopPlayback(
                pb.PlaybackRef(playback_id=playback.playback_id), metadata=metadata
            )
            continue

        stop_sent = time.time()
        stub.StopPlayback(
            pb.PlaybackRef(playback_id=playback.playback_id), metadata=metadata
        )
        stop_acked = time.time()

        stopped_at, stopped = bus.wait_for(
            "playback_stopped", WAIT_SECONDS, playback_id=playback.playback_id
        )

        row = {
            "iteration": iteration,
            "playback_id": playback.playback_id,
            "speech_track": speech.speech_started.track,
            "start_to_playing_ms": (playing_at - start_acked) * 1000,
            "report_to_event_ms": (arrival - reported) * 1000,
            "decide_ms": (stop_acked - arrival) * 1000,
            "cut_through_ms": (stop_acked - reported) * 1000,
            "start_rpc_ms": (start_acked - start_sent) * 1000,
            "stop_rpc_ms": (stop_acked - stop_sent) * 1000,
            "bus_ms": (arrival - event_at(speech)) * 1000,
        }
        if stopped is not None:
            row["stop_to_stopped_ms"] = (stopped_at - stop_acked) * 1000
            row["skew_ms"] = (
                event_at(stopped) - (stop_sent + stop_acked) / 2
            ) * 1000
        rows.append(row)
        log(
            "iteration {iteration}: cut_through {cut_through_ms:.1f} ms "
            "(report+bus {report_to_event_ms:.1f} + decide {decide_ms:.1f})".format(**row)
        )
        time.sleep(GAP_SECONDS)

    if consumer.failure:
        log(f"the consumer stream ended: {consumer.failure}")
    log(f"the consumer received {consumer.frames} audio frames while measuring")
    consumer.close()

    with open(OUT, "w") as handle:
        for row in rows:
            handle.write(json.dumps(row) + "\n")

    if not rows:
        raise SystemExit("no iteration completed; nothing to report")

    metrics = [
        "cut_through_ms",
        "report_to_event_ms",
        "decide_ms",
        "start_to_playing_ms",
        "bus_ms",
        "stop_rpc_ms",
        "start_rpc_ms",
        "stop_to_stopped_ms",
    ]
    summary = {
        "iterations_requested": ITERATIONS,
        "iterations_measured": len(rows),
        "events_missed": misses,
        "broker": BROKERS,
        "topic": TOPIC,
        "control": CONTROL,
        "attachment": ATTACHMENT,
        "trigger": "ConsumerToServer.SpeechReport(STARTED) on MediaStream",
        "skew_estimate_ms": round(
            percentile([row["skew_ms"] for row in rows if "skew_ms" in row], 0.5), 2
        ),
        "stats": [
            summarize(name, [row[name] for row in rows if name in row])
            for name in metrics
        ],
    }
    print(json.dumps(summary, indent=2), flush=True)
    log(f"per-iteration rows in {OUT}")


if __name__ == "__main__":
    main()
